---
title: 'Ch2: Statistical Learning Labs and Exercises'
author: "Kylie"
date: "30/03/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse) # loads packages including ggplot2
knitr::opts_chunk$set(echo = TRUE)
```

# Labs

In general you should use `<-` instead of `=` to assign values to variables, etc.

## 2.3.2 Graphics

An alternative to the suggested `plot` is to use `ggplot`. `ggplot` is useful for more complicated plots. 

```{r plot}
x = rnorm(100) # setting x to a vector of 100 random numbers with a mean of 0 and a standard deviation of 1
y = rnorm(100)

# Using plot to plot a scatterplot:
plot(x, y)
plot(x, y, xlab = "this is the x-axis", ylab = "this is the y-axis",
     main = "Plot of X vs Y")

# Alternatively, using ggplot to plot a scatterplot
# Need to make a data frame or tibble for the data we want to plot with ggplot:
data = tibble(y,x)

ggplot(data, aes(x, y)) +
  geom_point() +
  labs(xlab = "this is the x-axis", ylab = "this is the y-axis",
       title = "ggplot2 Plot of X vs Y")

```

It is easy to save plots created using `ggplot` as many different file types.

```{r plot_save}
x = rnorm(100) # setting x to a vector of 100 random numbers with a mean of 0 and a standard deviation of 1
y = rnorm(100)
# Need to make a data frame or tibble for the data we want to plot with ggplot:
data = tibble(y,x)

# Saving plot as pdf:
pdf ("Figure.pdf")
plot(x,y,col = "green")
dev.off ()

# Alternatively, saving ggplot using ggsave
a <- ggplot(data, aes(x, y)) +
  geom_point(color = "green") +
  labs(xlab = "this is the x-axis", ylab = "this is the y-axis",
       title = "ggplot2 Plot of X vs Y")
ggsave("Figure_ggplot.pdf", a)

```

```{r contour}
x <- seq(-pi ,pi ,length =50)
y <- x
f <- outer(x, y, function(x, y) cos(y)/(1 + x^2))
fa <- (f-t(f))/2

data <- tibble(x, y, fa)

# Using contour:
contour(x, y, f) # basic contour plot
contour(x, y, f, nlevels = 45, add=T)
contour (x, y, fa, nlevels = 15)

# Contour seems to be a better option than the ggplot version
```

```{r image}
# Using image:
image(x, y, fa)

# Alternatively using ggplot and geom_tile
ggplot(data, aes(x = x, y = y, fill = fa)) +
  geom_tile()

persp(x, y, fa)
persp(x, y, fa, theta =30)
persp(x, y, fa, theta =30, phi =20)
persp(x, y, fa, theta =30, phi =70)
persp(x, y, fa, theta =30, phi =40)
```

## 2.3.4 Loading Data

Here are some alternatives to `read.table()`:

```{r load}
# Importing .data file:
Auto <- read.table ("Auto.data", header = T, na.strings = "?")
fix(Auto)

read_delim("Auto.data", delim = "
           ") #seems more complicated than read.table

# Importing .csv file:
Auto <- read.csv("Auto.csv", header =T,na.strings ="?") # Auto is a data frame

Auto_2 <- read_csv("Auto.csv") # Auto_2 is a tibble. Don't need to specify that there is a header, missing values ("?") are imported as NA automatically


```

## 2.3.5 Additional Graphical and Numerical Summaries